"""add event registrations

Revision ID: 0362ae27add3
Revises: 507784d1d827
Create Date: 2026-09-11 16:19:39.468065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0362ae27add3'
down_revision: Union[str, Sequence[str], None] = '507784d1d827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('attendee_names', sa.Text(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_registrations')
    # ### end Alembic commands ###
