"""add wants_live_assessment to event_registrations

Revision ID: 182d2599c669
Revises: 0362ae27add3
Create Date: 2026-09-16 17:39:16.341133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182d2599c669'
down_revision: Union[str, Sequence[str], None] = '0362ae27add3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Adjusted from the autogenerated version: a bare NOT NULL column with no
    # default would fail against any registration rows that already exist
    # (real signups are already landing in production) - server_default
    # backfills every existing row to False, matching "didn't opt in" for
    # anyone who registered before this field existed.
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('wants_live_assessment', sa.Boolean(), nullable=False, server_default=sa.false())
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_column('wants_live_assessment')

    # ### end Alembic commands ###
