"""team_users email no longer unique - shared inbox

Revision ID: 794974ad6ac9
Revises: cb326ae8d548
Create Date: 2026-09-19 22:02:37.840998

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '794974ad6ac9'
down_revision: Union[str, Sequence[str], None] = 'cb326ae8d548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Written by hand, not autogenerated: Alembic's SQLite comparator didn't
    # detect this at all (the unique=True on the model becomes an implicit
    # sqlite_autoindex, not a named constraint it diffs), and a first attempt
    # using plain batch_alter_table().alter_column() looked like it worked
    # but was verified NOT to actually drop the constraint - batch mode
    # reflects and preserves the existing table's constraints unless the
    # replacement table is spelled out explicitly. Recreating by hand here
    # instead of trusting inference, verified directly against a real copy
    # of the production database before this was ever applied to the real
    # one - see backend/README.md's own warning about autogenerate.
    op.execute("ALTER TABLE team_users RENAME TO team_users_old")
    op.execute(
        """
        CREATE TABLE team_users (
            id INTEGER NOT NULL,
            email VARCHAR NOT NULL,
            display_name VARCHAR NOT NULL,
            status VARCHAR NOT NULL,
            webauthn_challenge VARCHAR,
            created_at VARCHAR NOT NULL,
            PRIMARY KEY (id)
        )
        """
    )
    op.execute(
        "INSERT INTO team_users (id, email, display_name, status, webauthn_challenge, created_at) "
        "SELECT id, email, display_name, status, webauthn_challenge, created_at FROM team_users_old"
    )
    op.execute("DROP TABLE team_users_old")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE team_users RENAME TO team_users_old")
    op.execute(
        """
        CREATE TABLE team_users (
            id INTEGER NOT NULL,
            email VARCHAR NOT NULL,
            display_name VARCHAR NOT NULL,
            status VARCHAR NOT NULL,
            webauthn_challenge VARCHAR,
            created_at VARCHAR NOT NULL,
            PRIMARY KEY (id),
            UNIQUE (email)
        )
        """
    )
    op.execute(
        "INSERT INTO team_users (id, email, display_name, status, webauthn_challenge, created_at) "
        "SELECT id, email, display_name, status, webauthn_challenge, created_at FROM team_users_old"
    )
    op.execute("DROP TABLE team_users_old")
