"""add team passkey auth and outreach tracking

Revision ID: cb326ae8d548
Revises: a6db21cd23b8
Create Date: 2026-09-18 09:48:49.884868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb326ae8d548'
down_revision: Union[str, Sequence[str], None] = 'a6db21cd23b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('webauthn_challenge', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('team_passkey_enroll_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('used_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['team_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['team_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token_hash')
    )
    op.create_table('team_webauthn_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sa.String(), nullable=True),
    sa.Column('device_label', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('last_used_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['team_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outreach_step1_sent_at', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('outreach_step2_sent_at', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('outreach_step3_sent_at', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('outreach_owner', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.drop_column('outreach_owner')
        batch_op.drop_column('outreach_step3_sent_at')
        batch_op.drop_column('outreach_step2_sent_at')
        batch_op.drop_column('outreach_step1_sent_at')

    op.drop_table('team_webauthn_credentials')
    op.drop_table('team_sessions')
    op.drop_table('team_passkey_enroll_tokens')
    op.drop_table('team_users')
    # ### end Alembic commands ###
